### ISSUE TITLE
windows line endings cause parseResources to fail

### ISSUE THREAD

**Issue by robjuhasz** [Schwartzkers/cvs-scm#2]
cvsRepository.parseResources receives 'stdout' with '\r\n' line endings on windows. 
fs.lstat() throws, nothing is displayed onn the source control UI

Fix is simple, either replace '\r\n' with '\n' before splitting the lines or trim the resulting lines. 
Now it works for me on windows 

```
	async parseResources(stdout: string): Promise<void> {
		const fs = require('fs/promises');
		this._sourceFiles = [];

		for (const element of stdout.split('\n').map(e=>e.trim())) {
```

**Comment by Schwartzkers** [comment]
Thank you for bringing this to my attention. I have incorporated your suggested fix in v1.5.0.
