### ISSUE TITLE
Option to checkout only some folders

### ISSUE THREAD

**Issue by heinrichreimer** [Schwartzkers/cvs-scm#3]
First, thanks for the plugin! Having rich diff for CVS inside my favorite editor means a lot to me.
One thing, I would find useful would be an option to checkout only some of the subdirectories from `CVSROOT`, especially when the repository is rather large.
If there's anything I can assist you with for implementation, please let me know.

**Comment by Schwartzkers** [comment]
Thank you for the feed back, it is appreciated. I'm glad the extension is helpful to others.

In the next version (1.6.0) I'll be adding a non-recursive folder download option. The user can review any discovered subfolders and decide which of those to ignore or download. I am also adding multi-select capability (hold Clrl and select multiple items then select a command such as stage/add/discard/etc). 

This may not be exactly what you are requesting, but hopeful it helps a little. Eventually, I plan to add a repository browser where folders can be download into the workspace, but I'll need some time to complete that work.

**Comment by heinrichreimer** [comment]
Works like a charm :+1:
