### ISSUE TITLE
Host key fingerprint ends up in the diff

### ISSUE THREAD

**Issue by heinrichreimer** [Schwartzkers/cvs-scm#4]
There's a minor visual bug in the diff view when using `extssh`.
On the bottom it always shows the host key fingerprint. Maybe that can be ignored somehow.
![Screenshot from 2022-11-14 12-08-27](https://user-images.githubusercontent.com/5065698/201645661-cb0e4779-b1a2-4c1b-9ef1-7e4bede4469b.png)

**Comment by Schwartzkers** [comment]
Thanks for bringing this to my attention. I've not noticed that issue while using remote ssh development and the CVS extension? I'll have to investigate how that is occurring. Does extssh actually add the key to the file from the command line and you just need a way to have it ignored by the CVS extension?

**Comment by heinrichreimer** [comment]
My `CVSROOT` looks like this: `:extssh:user@example.com:/srv/cvsroot`.
The fingerprint gets added by the SSH client. For example if I SSH to that server it says:
```
Host key fingerprint is SHA256:0+jMOwuXH1eGDE9+zECarg6DWVYp2gC86wNQb35jKws
+---[ECDSA 256]---+
| ..         .    |
|  o.     . +     |
| . o. . o + o    |
|. . o+ o + * =   |
|.  +. + S o = *  |
|. . .=++ +   +   |
| oE oo+oB . .    |
|  o.. .*.o o     |
|   ..o  +o.      |
+----[SHA256]-----+
Last login: Mon Nov XX XX:XX:XX 2022 from XXX.XXX.XXX.XXX
```
The fingerprint also appears when executing CVS commands, e.g., `cvs update`:
```
Host key fingerprint is SHA256:0+jMOwuXH1eGDE9+zECarg6DWVYp2gC86wNQb35jKws
+---[ECDSA 256]---+
| ..         .    |
|  o.     . +     |
| . o. . o + o    |
|. . o+ o + * =   |
|.  +. + S o = *  |
|. . .=++ +   +   |
| oE oo+oB . .    |
|  o.. .*.o o     |
|   ..o  +o.      |
+----[SHA256]-----+
cvs update: Updating .
P XXXXXXXX.txt
cvs update: Updating XXXXXXX
cvs update: Updating XXXXXXX
U XXXXXXXXX/XXXXXXXX.txt
...
```
Maybe the fingerprint therefore also occurs in some command that the extension calls internally.
It won't be appended to any file AFAIK. Only on the command line.
In any way, it can be ignored.

**Comment by heinrichreimer** [comment]
It's fixed. Thanks a lot!
