### ISSUE TITLE
"Changes" view with wrong encoding

### ISSUE THREAD

**Issue by viniiivs** [Schwartzkers/cvs-scm#9]
In the 'Changes' view, the left file that is opened does not adhere to the configured encoding settings, unlike the right file. As a result, it becomes challenging to review the changes due to the presence of '�' characters. Could the encoding configuration be adjusted to ensure consistency in the encoding setting for both files?"

![image](https://github.com/Schwartzkers/cvs-scm/assets/26415276/b4dee047-7cdb-40a9-864a-993931f7b0e1)

**Comment by Schwartzkers** [comment]
That is strange. I’ll have to investigate to determine if there’s anything I can do in the extension. I use the built in VS Code diff API for the Changes view. On the right is your working copy and the left is the output from  “cvs -Q update -C -p <filename>” (stdout). I’ve not adjusted any encoding so everything should be using the defaulting encoding from the vs code settings.

Do you see the encoding issue if you run the "cvs -Q update -C -p <filename>" command from a terminal?

Not sure is this following will help:
https://stackoverflow.com/questions/38528384/how-to-setup-visual-studio-code-to-detect-and-set-the-correct-encoding-on-file-o

I’ll continue to investigate if there’s anything I can do in the extension to resolve the issue. 

Thank you for bringing this to my attention.

**Comment by viniiivs** [comment]
I tried using the command "cvs -Q update -C -p" but it printed so much that I couldn't tell if it was right or not. It might be something related to my repository.
However, the option to identify the encoding did not work. Nor forcing to always open with a specific encoding.
I'm glad you were able to reproduce the issue, anything I can help with let me know.

**Comment by GergelyZsolt** [comment]
It's a problem for me too. Couldn't it be solved in a way similar to the patch below? Unfortunately, I couldn't try it.

File to modify: utility.ts

```
-import { Uri } from 'vscode';
+import { Uri, workspace } from 'vscode';
 import { cvsCommandLog } from './extension';

 export class CmdResult {
@@ -60,7 +60,7 @@

         const cmd = spawn(cvsCommand, [""], options);

-        cmd.stdout.setEncoding('utf8');
+        cmd.stdout.setEncoding(workspace.getConfiguration('files').get<string>('encoding') || 'utf8');
         cmd.stderr.setEncoding('utf8');

         cmd.stdout.on("data", (data: any) => {
```

**Comment by Schwartzkers** [comment]
I agree, this issue makes it very difficult to review changes. I've tried several fixes and none of them have resolved the issue. And unfortunately the proposed fix from GergelyZsolt did not work either. 

I'll keep investigating. I'm open to any suggestions if you have any thoughts on how to resolve.

**Comment by Schwartzkers** [comment]
@viniiivs  Thank you for the analysis. It was very helpful and appreciated!

I released version 1.13.0 (pre-release) today with a slightly different approach, but based on your findings and some reading of node.js buffer encoding for ISO-8859-1. I liked how you added a config item for encoding, but I'm not sure yet if I want to keep it as a configuration item at this point.

Hopeful the pre-release will work for you and the code diff will be more useful.

**Comment by Schwartzkers** [comment]
Excellent! Thank-you for letting me know it worked @viniiivs .

I'll continue to explore the encoding solution. I'm curious/worried how many other encoding types have a similar problem?

Your solution has given me someone to think about on how to allow the user to "work around" the issue on their own.

Cheers!

**Comment by GergelyZsolt** [comment]
I am currently working on a solution based on how the git plugin works. This would handle all encoding and auto-guessing as well.

**Comment by GergelyZsolt** [comment]
I sent the pull request yesterday: #11 

I tested it in a latin2 repository. Please try it to see if it works well for you too. I hope that a good solution can be prepared based on this.

**Comment by Schwartzkers** [comment]
@GergelyZsolt your changes have been merged into the latest pre-release (v1.13.1). I made a few edits to respect copyright ethics. Thanks again for your efforts!

I did some basic testing with the changes. Everything seems to be working. I'll turn the release into a full release after some soak time to ensure no adverse affects are caught.

**Comment by viniiivs** [comment]
@Schwartzkers in the new pre release, my vscode didn't recognize the folder as a cvs repository.
![image](https://github.com/Schwartzkers/cvs-scm/assets/26415276/74cec9be-ba7d-4e26-8e75-1cab4d9a1ca5)

![image](https://github.com/Schwartzkers/cvs-scm/assets/26415276/deb18f3c-37a4-48be-bd33-0f423571912b)

**Comment by Schwartzkers** [comment]
@viniiivs The issue should now be fixed with v1.13.2. I forgot to add the run-time dependencies.

**Comment by GergelyZsolt** [comment]
Sorry about the dependencies error, it was my fault. The pre-release works fine for me now.

I even tried handling stderr with a corrupted .cvspass file in debug mode, but I didn't experience any errors.

**Comment by Schwartzkers** [comment]
@GergelyZsolt No worries, I should have caught this issue in my release testing, but I got a little lazy and skipped a step. I usually make a vsix package and test installing it and running it. The good news is that I can make pre-releases where users will be more understanding if an error occurs.

Thanks for testing it out. I'll give the pre-release a few weeks before promoting it to v1.14.0.

**Comment by GergelyZsolt** [comment]
Any updates here? When will it be released?

**Comment by Schwartzkers** [comment]
@GergelyZsolt  Have you been using the pre-release? I can release it officially, but first can you confirm the pre-release is working as expected for you?

**Comment by GergelyZsolt** [comment]
> @GergelyZsolt Have you been using the pre-release? I can release it officially, but first can you confirm the pre-release is working as expected for you?

I have been actively using since the pre-release and have not experienced any problems.

**Comment by Schwartzkers** [comment]
1.14.0 is now released with the fix.
